services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: vertx-share-broker
      # Use root/secret user/password credentials
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3307:3306

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8081:8080

#permanent storage of data
# > docker volume rm mysql_vertx-share-broker-data-local
volumes:
  vertx-share-broker-data-local:
